In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ast import literal_eval

In [15]:
data_movies = pd.read_csv('C:\\Users\\ujwal\\Downloads\\movies.csv',na_filter=False)

In [16]:
data_movies = data_movies.drop(columns=['title', 'tagline', 'status', 'homepage', 
                                       'popularity', 'production_companies', 'budget',
                                       'production_countries','keywords','overview','runtime','spoken_languages','release_date', 'revenue',
                                         'original_language'])

In [17]:
features = ['genres']
for feature in features:
    data_movies[feature] = data_movies[feature].apply(literal_eval)

In [18]:
def get_list(meta_data):
    if isinstance(meta_data, list):
        names = [col['name'] for col in meta_data]
        if len(names) > 3:
            names = names[:3]
        return names
    return []

features = ['genres']
for feature in features:
    data_movies[feature] = data_movies[feature].apply(get_list)

In [19]:
data_movies = data_movies.drop('genres', 1).join(
    pd.get_dummies(
        pd.DataFrame(data_movies.genres.tolist()).stack()
    ).astype(int).sum(level=0)
)

In [20]:
data_movies.head(5)

,movie_id,original_title,vote_average,vote_count,Action,Adventure,Animation,Comedy,Crime,Documentary,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,426469,Growing Up Smith,7.4,7,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,325373,Two Lovers and a Bear,6.8,27,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,374461,Mr. Church,7.0,129,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,385736,Kicks,7.5,18,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,339408,The Birth of a Nation,6.5,178,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
data_movies.dropna()

,movie_id,original_title,vote_average,vote_count,Action,Adventure,Animation,Comedy,Crime,Documentary,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,426469,Growing Up Smith,7.4,7,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,325373,Two Lovers and a Bear,6.8,27,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,374461,Mr. Church,7.0,129,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,385736,Kicks,7.5,18,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,339408,The Birth of a Nation,6.5,178,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,63574,Joyful Noise,6.7,33,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
995,77866,Contraband,6.1,770,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
996,76487,The Devil Inside,4.6,262,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
998,71688,The Iron Lady,6.2,527,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,72766,Newlyweds,5.9,5,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [22]:
data_movies.to_csv (r'C:\Users\ujwal\Downloads\Recommendations_DataSet_Genre.csv', index = False, header=True)